apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-express
  template:
    metadata:
      labels:
        app: hello-world-express
    spec:
      containers:
        - name: hello-world-express
          image: walpolsh/hello-world-express:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-express-service
spec:
  selector:
    app: hello-world-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
